**It’s a Python-based scientific computing package targeted at two sets of audiences:**
*   A replacement for NumPy to use the power of GPUs
*   A deep learning research platform that provides maximum flexibility and speed


---



---



**Tensors**

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

In [2]:
torch.cuda.is_available()  # will be true if set to GPU

True

In [3]:
x = torch.empty(5, 3, device="cuda")    # an uninitialized 5X3 matrix on cuda if specified else cpu
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')


In [4]:
x = torch.rand(5, 3)  # a randomly initialized 5X3 matrix
print(x)

tensor([[0.5956, 0.2948, 0.3530],
        [0.5891, 0.4295, 0.6258],
        [0.4083, 0.6453, 0.1288],
        [0.9039, 0.6605, 0.2167],
        [0.1623, 0.8534, 0.9876]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
print(x.size()) # to know the size of the tensor 

torch.Size([5, 3])


In [7]:
x = torch.tensor([4.3, 2, 9.1])
print(x)

tensor([4.3000, 2.0000, 9.1000])


**Operations on Tensors**

In [8]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x+y)  # we can also write print(torch.add(x, y))

tensor([[0.7175, 0.8608, 1.9190],
        [1.3038, 0.1673, 0.9532],
        [1.2473, 1.3441, 1.3589],
        [0.0739, 0.4485, 1.8162],
        [0.8617, 1.0023, 1.1947]])


In [9]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
ans = torch.empty(5, 3)
torch.add(x, y, out=ans)  # providing the output as argument
print(ans)

tensor([[0.5466, 0.4467, 0.7677],
        [1.3153, 1.3988, 1.0223],
        [0.9971, 0.7665, 1.0782],
        [1.8754, 0.4651, 1.0439],
        [0.9352, 1.3109, 1.1425]])


In [10]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
x.add_(y)  # inplace adding  NOTE: In pytorch any function ending with _ will do inlace operation
print(x)

tensor([[0.3808, 1.5858, 1.2997],
        [1.2195, 1.3651, 1.1054],
        [1.5741, 0.5097, 1.5868],
        [0.9870, 0.7605, 1.1556],
        [0.3553, 1.6764, 1.1582]])


In [11]:
print(x[:, :2])  # slicing similar to numpy

tensor([[0.3808, 1.5858],
        [1.2195, 1.3651],
        [1.5741, 0.5097],
        [0.9870, 0.7605],
        [0.3553, 1.6764]])


In [12]:
x = torch.randn(5, 3)  # rand samples from U(0, 1) and randn samples from N(0, 1)
print(x)

tensor([[-1.4107,  0.6423,  0.6161],
        [-0.1625, -1.5269,  1.3150],
        [ 1.4236, -1.5463, -1.1075],
        [ 0.3638,  0.0501,  0.6722],
        [-2.0409,  0.0623,  1.0181]])


In [13]:
y = x.view(15)  # resizing using view
print(y)

tensor([-1.4107,  0.6423,  0.6161, -0.1625, -1.5269,  1.3150,  1.4236, -1.5463,
        -1.1075,  0.3638,  0.0501,  0.6722, -2.0409,  0.0623,  1.0181])


In [14]:
z = x.view(3, 5)
print(z)

tensor([[-1.4107,  0.6423,  0.6161, -0.1625, -1.5269],
        [ 1.3150,  1.4236, -1.5463, -1.1075,  0.3638],
        [ 0.0501,  0.6722, -2.0409,  0.0623,  1.0181]])


In [15]:
print(x.size())
print(y.size())

torch.Size([5, 3])
torch.Size([15])


In [16]:
x = torch.rand(1)
print(x)
print(x.item())  # if we have only one element we can use .item to get that element

tensor([0.9682])
0.9682096242904663


**Numpy Bridge**

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one inplace will change the other.

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
a = a+1
print(a)

tensor([2., 2., 2., 2., 2.])


In [19]:
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
x = torch.ones(5, 5, dtype=torch.int)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)


In [22]:
x = torch.randn(3, 5)
y = torch.rand(3, 5)
# element wise operations
z = torch.add(x, y)
w = torch.sub(x, y)
t = torch.mul(x, y)
print(z)
print(w)
print(t)

tensor([[ 1.4283, -1.9666, -1.8957,  0.1665, -0.1555],
        [ 1.2359,  1.6346,  2.3518,  0.3384,  0.4834],
        [ 1.2343,  1.0526,  2.0202,  1.8195, -0.2721]])
tensor([[ 1.3649, -3.6302, -2.3774, -1.8155, -0.8809],
        [ 1.2180,  0.0511,  1.2697, -1.4619, -0.7774],
        [ 0.3217,  0.0365,  0.8503,  1.7138, -1.2897]])
tensor([[ 0.0443, -2.3277, -0.5147, -0.8171, -0.1879],
        [ 0.0110,  0.6674,  0.9797, -0.5056, -0.0927],
        [ 0.3550,  0.2767,  0.8396,  0.0934, -0.3973]])


In [23]:
torch.cuda.is_available()

True

In [24]:
x = torch.eye(5, 5, device="cuda", dtype=torch.int)  # identity matrix
print(x)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]], device='cuda:0', dtype=torch.int32)


In [25]:
x = torch.arange(0, 10, 2)  # from 0 to excluding 10 with step of 2
print(x)

tensor([0, 2, 4, 6, 8])


In [26]:
x = torch.linspace(1, 10, 10) # from 1 to 10 including 10 values
print(x)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [27]:
x = torch.rand(2, 5)
y = torch.randn(5, 4)
z = torch.mm(x, y)  # matrix multiplicatio?n
print(z)
print(z.size())

tensor([[-0.0333,  0.6263, -0.4645,  0.5524],
        [ 0.0598, -0.0675, -1.0529,  0.1156]])
torch.Size([2, 4])
